### ISSUE TITLE
Body parse strategy

### ISSUE THREAD

**Issue by zhaoyao91** [Masquerade-Circus/micro-ex-router#3]
I think the current body parse strategy has some problems:

1. all content type of text/* should be parsed as text.
2. if no rule could be applied, the body should be left as it is.
3. there should be some options to disable default body parsing.

**Comment by Masquerade-Circus** [comment]
Thanks for your comment.
I think the logic you mention is correct, and as soon as I can, I will update the plugin.
Thank you.

**Comment by Masquerade-Circus** [comment]
Body parse strategy changed on: https://github.com/Masquerade-Circus/micro-ex-router/commit/6aa07c6eda5dc31326f2a02751963d7cafd46e6b
